FROM python:3-slim-buster

ADD requirements.txt /opt/requirements.txt

RUN apt-get update \
    && apt-get install -y calibre \
    && pip install -r /opt/requirements.txt

# CMD ["python", "/opt/e-threader/main.py"]
